services:
  postgreSql:
    image: postgres:latest
    container_name: postgreSql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      TZ: Asia/Tokyo
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
      - ./db-init/postgres:/docker-entrypoint-initdb.d
    networks:
      - myNetwork
  
  pgweb: 
    image: sosedoff/pgweb
    container_name: pgweb
    ports:
      - "8081:8081"
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgreSql:5432/postgres?sslmode=disable
    links:
      - postgreSql
    restart: always
    depends_on:
      - postgreSql
    networks:
      - myNetwork
  
  mongoDb:
    image: mongo:4.4.18
    container_name: mongoDb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
      MONGO_INITDB_DATABASE: jojihouse
      TZ: Asia/Tokyo
    volumes:
      - ./data/mongodb:/data/db
      - ./db-init/mongo:/docker-entrypoint-initdb.d
    networks:
      - myNetwork
  
  jojihouse-system:
    build: ./entrance-system
    container_name: jojihouse-system
    ports:
      - "8080:8080"
    depends_on:
      - postgreSql
      - mongoDb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=postgreSql
      - POSTGRES_PORT=5432

      - MONGO_USER=mongo
      - MONGO_PASSWORD=mongo
      - MONGO_DB=jojihouse
      - MONGO_HOST=mongoDb
      - MONGO_PORT=27017
    volumes: 
      - ./entrance-system:/go/src
    tty: true
    networks:
      - myNetwork

networks:
  myNetwork:
    driver: bridge
    ipam:
      driver: default
