services:
  postgreSql:
    image: postgres:latest
    container_name: postgreSql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      TZ: Asia/Tokyo
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
      - ./db-init/postgres:/docker-entrypoint-initdb.d
    restart: always
    networks:
      - myNetwork
  
  pgweb: 
    image: sosedoff/pgweb
    container_name: pgweb
    ports:
      - "8081:8081"
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgreSql:5432/postgres?sslmode=disable
    restart: always
    depends_on:
      - postgreSql
    networks:
      - myNetwork
  
  mongoDb:
    image: mongo:4.4.18
    container_name: mongoDb
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
      MONGO_INITDB_DATABASE: jojihouse
      TZ: Asia/Tokyo
    volumes:
      - ./data/mongodb:/data/db
      - ./db-init/mongo:/docker-entrypoint-initdb.d
    restart: always
    networks:
      - myNetwork
  
  jojihouse-system:
    build: 
      context: ./entrance-system
      # dockerfile: Dockerfile.air
      dockerfile: Dockerfile
    container_name: jojihouse-system
    ports:
      - "8080:8080"
    depends_on:
      - postgreSql
      - mongoDb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=postgreSql
      - POSTGRES_PORT=5432

      - MONGO_USER=mongo
      - MONGO_PASSWORD=mongo
      - MONGO_DB=jojihouse
      - MONGO_HOST=mongoDb
      - MONGO_PORT=27017
    restart: always
    tty: true
    networks:
      - myNetwork

  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Tokyo
      - SERVERURL=your.domain.com # または外部からのグローバルIP
      - SERVERPORT=51820
      - PEERS=admin # VPNクライアント名（複数可: admin,developer など）
      - PEERDNS=auto
      - INTERNAL_SUBNET=10.13.13.0 # VPN内部サブネット
    volumes:
      - ./config/wireguard:/config
      - /lib/modules:/lib/modules
    ports:
      - "51820:51820/udp" # WireGuardポートのみ外部公開
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: always
    networks:
      - myNetwork

networks:
  myNetwork:
    driver: bridge
    ipam:
      driver: default
