services:
  postgreSql:
    image: postgres:latest
    container_name: postgreSql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
    networks:
      myNetwork: 
        ipv4_address: 172.30.0.2
  
  pgweb: 
    image: sosedoff/pgweb
    container_name: pgweb
    ports:
      - "8081:8081"
    environment:
      DATABASE_URL: postgres://postgres:postgres@172.30.0.2:5432/postgres?sslmode=disable
    links:
      - postgreSql
    restart: always
    depends_on:
      - postgreSql
    networks:
      myNetwork: 
        ipv4_address: 172.30.0.3
  
  mongoDb:
    image: mongo:latest
    container_name: mongoDb
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongodb:/data/db
    networks:
      myNetwork:
        ipv4_address: 172.30.0.11

networks:
  myNetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24