services:
  postgreSql:
    image: postgres:latest
    container_name: postgreSql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    networks:
      myNetwork: 
        ipv4_address: 172.30.0.2
  
  mongoDb:
    image: mongo:latest
    container_name: mongoDb
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongodb:/data/db
    networks:
      myNetwork:
        ipv4_address: 172.30.0.3

networks:
  myNetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24